### ISSUE TITLE
multiple package error when I use swift test

### ISSUE THREAD

**Issue by staufga0** [cui-unige/semantique#10]
After doing the rm, when I try to run swift test I encounter the following error : 
error: Found multiple packages with the name Parsey: https://github.com/rxwei/Parsey, https://github.com/kyouko-taiga/Parsey.git

I use the Swift version 4.0.3 (swift-4.0.3-RELEASE)

**Comment by QuentinRiv** [comment]
Has any solution been found yet ?

**Comment by saucisson** [comment]
We have found the problem, the pull request is currently being merged.

**Comment by saucisson** [comment]
It should be fixed now. Can you do:

```
$ rm -rf Package.resolved .build/
$ swift test
```

**Comment by QuentinRiv** [comment]
It's fixed. The test can be running correctly.
Thank you

**Comment by saucisson** [comment]
Sorry for the delay.
