### ISSUE TITLE
TP2 - What result 

### ISSUE THREAD

**Issue by QuentinRiv** [cui-unige/semantique#12]
In Homework #2, our logic programm is supposed to "return at least one answer if the typing is correct, and no answer if the typing is incorrect".
But when is it supposed to return this ? Like in TP1, should we have "Before" and "After" the visitor ? Or should the answer (if there is) be returned from the CheckTypesVisitor structure ?

**Comment by saucisson** [comment]
The visitor contains a `kb` field, that is the knowledge base, and a `variables` field that maps variables in Anzen to variables in LogicKit.
You have to fill these two structures while walking through the Anzen program, such that i can later ask the knowledge base what is the type of a variable. The question will be like: `typeOf[x, isInteger]`.

**Comment by QuentinRiv** [comment]
Okay, thank you for the answer.
But how are we supposed to fill the `kd` structure if kd.knowledge is a let constant, and so impossible to mutate (except if we do so at the beginning of the Anzen program ?)

**Comment by saucisson** [comment]
`kb` is a `var` and can thus be modified in the same way as `bindings` in the previous homework.

**Comment by QuentinRiv** [comment]
Oh, that's right .
(Actually, my mistake was juste trying to use `.append`)
Thank you

**Comment by QuentinRiv** [comment]
One last question : when we have, in `kb`
