### ISSUE TITLE
TP2 - Kind of answer

### ISSUE THREAD

**Issue by QuentinRiv** [cui-unige/semantique#13]
What should be the 'answer' for this kind of PropDecl : `let x : Int = 1 + 2 + 3`
Should it be something like :
`type-of[1, isInteger]`
`type-of[2, isInteger]`
`type-of[3, isInteger]`
`type-of[x, isInteger]`
`type-of[add[add[1, 2], 3], isInteger]`
`type-of[add[add[1, 2], 3], t] => type-of[x, t]`

Or more something juste like this :
`type-of[x, isInteger]`

**Comment by saucisson** [comment]
The latter: `type-of[x, isInteger]`, because `type-of[1, isInteger]` and `type-of[1, t] => type-of[x, t]`.
Warning: `x` is a LogicKit variable that is mapped to the Anzen AST node for the declaration of the Anzen variable `x`.
