### ISSUE TITLE
Homework #2 content of knowledge base

### ISSUE THREAD

**Issue by CorentinB74** [cui-unige/semantique#14]
Does the `kb` variable only consist of : 
`typeOf[x,isInteger], typeOf[y, isString], ...` ?

**Comment by saucisson** [comment]
Yes, it should only contain such statements, also with implications: `typeOf[x, t] => typeOf[y, t]` for instance.

**Comment by CorentinB74** [comment]
Why such implications? What is their purpose?

**Comment by CorentinB74** [comment]
Thanks for the answer. One last question, do we have to propagate constants first before checking types?
If so, we can check whether a statements has been reduced or not to determine if the typing is correct.

**Comment by saucisson** [comment]
No, you do not have to perform constant propagation.
