### ISSUE TITLE
Incorrect Typing

### ISSUE THREAD

**Issue by QuentinRiv** [cui-unige/semantique#16]
For this kind of incorrect typing :
`let x : Int = 1` 
`x = true`
what should be the answer in `kb` ?

No return, as you said in the ReadMe ("no answer if the typing is incorrect"), or several contradictory _typeOf_, such as `type-of[x, isInteger]` and `type-of[x, isBool]` (as you said Issues #13 )

**Comment by saucisson** [comment]
Here, there would be several contradictory answers.
