### ISSUE TITLE
Stefan's presentation on GitHub

### ISSUE THREAD

**Issue by lutzilutz** [cui-unige/semantique#21]
Could you post the presentation of Stefan about GitHub ? I think it could be really useful for this course and further works for most of us, as it was clear and helpful. Thanks !

**Comment by saucisson** [comment]
@stklik can you please put in in this repository?

**Comment by stklik** [comment]
Added into main repository via upload.
File is currently [here](https://github.com/cui-unige/semantique/blob/master/git-basics.pdf).
Feel free to move it.
