### ISSUE TITLE
Dealing with IfExpr

### ISSUE THREAD

**Issue by QuentinRiv** [cui-unige/semantique#25]
How are we supposed to "verify" the IfExpressions ? Because, since we cannot check the condition, and so whether we execute the thenBlock, or the elseBlock, we should logically check the references in both parts (right ?). But what if the thenBlock part is entirely correct, but not the elseBlock ? Which one do we check ? Or should we evaluate the condition, so that we execute only one block ?

**Comment by saucisson** [comment]
Yes you have to verify that both parts of the `if` expressions are consistent.
If only one of the block is incorrect, the the whole `if` expression is incorrect.

**Comment by QuentinRiv** [comment]
Okay, thank you for the answer.
Still about an IfExpr (and, in general, about blocks) : 
What happen in this kind of situtation : 
`let x = 5`
`let y &- x`
`{
x = 1
}`

At the end, on what will be the reference of `x` ? On `5` or on `1` (which would an error on `y` ) ?

**Comment by saucisson** [comment]
@kyouko-taiga ?

**Comment by saucisson** [comment]
I would say that there is a problem, because `y` refers to `5` that has no owner at the end of the block.
