### ISSUE TITLE
TP #4 - Error with y <- x

### ISSUE THREAD

**Issue by QuentinRiv** [cui-unige/semantique#28]
In the tests, I have this ModulDecl : 
`let x = 1`
`var y = 5`
`y <- x`

I would expect  `y` becoming the owner of `1`, right ?
But it seems there is a problem with that : the parser understand the last statement, which should be a`BindingStmt`, as a `BinExpr` like `y < -x` (a test if y is smaller than -x)

Do we have to change something ? Or is it impossible to do such a reference like this as a BindingStmt ?

**Comment by saucisson** [comment]
If the parser does not understand correctly this statement, there is nothing you can do...
@kyouko-taiga
