### ISSUE TITLE
For any block expressions, how are we supposed to handle the results?

### ISSUE THREAD

**Issue by attilaM68K** [cui-unige/semantique#29]
For any block experessions, like IfExpr, functions, how are we supposed to indicate that the "whole block" is false? From what I see we can't indicate it in variables since it takes PropDecl's as labels in the dictionary and there's no way we can identifiy a IfExpr, for example, with a PropDecl. As it stands, the only thing I can do is to indicate any mishandled variables in the blocks. Unless you implicitly want us to create yet another dictionary for each type of block, there's no way to indicate that a whole block is false. Also, how are we able to check whether a  variable is constant or not? I can't find the way to do it.

**Comment by saucisson** [comment]
You do not tell that a block is true or false. You have to give the `true` or `false` value to Anzen variables declaration.
