### ISSUE TITLE
Error when compiling, after updating using the instructions in the readme

### ISSUE THREAD

**Issue by attilaM68K** [cui-unige/semantique#30]
I have the following error when trying to compile without any modifications to the source file:
`/home/username/projects/semantique/Sources/semantique/CheckReferencesVisitor.swift:14:29: error: use of undeclared type 'Boolean'
  var variables: [PropDecl: Boolean] = [:]
                            ^~~~~~~
/home/username/projects/semantique/Sources/semantique/CheckReferencesVisitor.swift:14:7: error: could not infer type for 'variables'
  var variables: [PropDecl: Boolean] = [:]
      ^
/home/username/projects/semantique/Sources/semantique/InterpretVisitor.swift:237:11: warning: no calls to throwing functions occur within 'try' expression
          try self.visit(parameter)
          ^
/home/username/projects/semantique/Sources/semantique/InterpretVisitor.swift:264:11: warning: no calls to throwing functions occur within 'try' expression
          try self.visit(arg)
          ^
/home/username/projects/semantique/Sources/semantique/PropagateConstantVisitor.swift:197:17: warning: no calls to throwing functions occur within 'try' expression
                try self.visit(parameter)
                ^
/home/username/projects/semantique/Sources/semantique/PropagateConstantVisitor.swift:219:17: warning: no calls to throwing functions occur within 'try' expression
                try self.visit(arg)
`
The last few warnings are due to not having written anything, but the only line that was given to us has a typing problem, since ,for some reason, "Boolean" is undefined. As far as I know, swift has "Bool" as a type not "Boolean"

**Comment by saucisson** [comment]
Replace `Boolean` by `Bool` and it should work.
