### ISSUE TITLE
Privacy

### ISSUE THREAD

**Issue by DavidRodriguezSoaresCUI** [cui-unige/semantique#4]
Hello,
I've read the instructions about how we're supposed to work on Github this semester.
One of them is that our fork must be private. The problem arises from the fact that, to the best of my knowledge, there is no other way to make a repository private other than paying for that "service".
What do you propose about this issue ?

**Comment by saucisson** [comment]
As told in the README: "Create an account, and do not forget to fill your profile with your full name and your University email address. Ask GitHub for a Student Pack to obtain free private repositories."
To ask the Student Pack, you have to register your `@etu.unige.ch` email address in GitHub.

**Comment by saucisson** [comment]
Using a private repository is **mandatory**. Please make your repository private.
