### ISSUE TITLE
Homework #1 Operators cpy, ref and mov

### ISSUE THREAD

**Issue by staufga0** [cui-unige/semantique#5]
In the list of anzen operators, I see three operators, cpy, ref and mov.
What do they do, how am I supposed to deal with them for the propagate constant visitor ?

**Comment by saucisson** [comment]
You can look at this [blog post](https://cui-unige.github.io/blog-smv/2018/03/02/assignment/) to understand the semantics of these operators in Anzen.
But short answer: you should handle all of them in the same way, as `=` in usual programming languages.
