### ISSUE TITLE
Homework #1 - If statements

### ISSUE THREAD

**Issue by CorentinB74** [cui-unige/semantique#7]
What should be the behavior of `PropagateConstantsVisitor` for if statements, like : 
```
var x = 2 
var y = 2
if x == y {
  y = x
  x = 18
} else {
  x = y
}
```
Do we have to replace it by 
```
var x = 2 
var y = 2
if true {
  y = 2
  x = 18
} else {
  x = 2
}
```
Or directly
```
var x = 2 
var y = 2
y = 2
x = 18
```

And what is the purpose of the following struct `LogicConstantsVisitor : ASTVisitor`.

Thanks in advance.

**Comment by saucisson** [comment]
First: it is a good question, you can do whatever version you want. The second is better.

The `LogicConstantsVisitor` will be used in the next homework, maybe. We do not have had time to learn about it during the exercises.

**Comment by CorentinB74** [comment]
Thank you for the answer, however how the second version is possible since there is not explicit cast to transforms an IfExpr to a single Block.

**Comment by saucisson** [comment]
You can maybe create a block... or if it not possible, then you cannot do the second version.

**Comment by kyouko-taiga** [comment]
What exactly are you trying to cast?

FYI, an `IfExpr` is composed of three `Node`s, for respectively the condition, the "then" branch and the "else branch". If you want to remove the conditional block and keep only a single branch, you may reassign the corresponding node in the AST.

For instance:
```swift
for i in 0 ..< block.statements.count {
  if let ifExpr = block.statements[i] as? IfExpr {
    block.statements[i] = ifExpr.thenBlock
  }
}
```
